name: xepy35
channels:
- defaults
- pytorch
- matsci
dependencies:
- python=3.5
- numpy
- pandas
- tqdm
- seaborn
- requests
- matplotlib
- plotly
- scikit-learn
- scipy
- pytorch
- pyyaml
- pip:
  - pymonad
  - pymatgen
  - matminer
