name: xepy36
channels:
- defaults
- pytorch
- matsci
dependencies:
- python=3.6
- numpy
- pandas
- tqdm
- seaborn
- pymatgen
- requests
- matplotlib
- plotly
- scikit-learn
- scipy
- pytorch
- pyyaml
- pip:
  - pymonad
  - matminer
