name: xepy36
channels:
  - defaults
  - pytorch
  - rdkit
dependencies:
  - python=3.6
  - pandas
  - seaborn
  - requests
  - rdkit
  - plotly
  - scikit-learn
  - scipy
  - pytorch
  - pytest
  - pytest-cov
  - pylint
  - sphinx
  - sphinx_rtd_theme
  - jupyter
  - pip:
      - ruamel.yaml
      - pymatgen
      - jupyterlab
      - yapf
