name: xepy35
channels:
  - defaults
  - pytorch
  - rdkit
dependencies:
  - python=3.5
  - pandas
  - seaborn
  - requests
  - rdkit=2018.09.2
  - plotly
  - scikit-learn
  - scipy
  - pytorch=1.0.1
  - pytest
  - pytest-cov
  - pylint
  - sphinx
  - sphinx_rtd_theme
  - jupyter
  - pip:
      - ruamel.yaml
      - pymatgen==2019.3.13
      - jupyterlab
      - yapf
      - tqdm
