name: xepy36
channels:
  - defaults
  - pytorch
  - conda-forge
  - matsci
dependencies:
  - python=3.6
  - numpy
  - pandas
  - seaborn
  - requests
  - matplotlib
  - rdkit
  - plotly
  - scikit-learn
  - scipy
  - pytorch
  - pytest
  - pytest-cov
  - pymatgen
  - pylint
  - sphinx
  - sphinx_rtd_theme
  - jupyter
