name: xepy35
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.5
  - pandas
  - seaborn
  - requests
  - rdkit
  - plotly
  - scikit-learn
  - scipy
  - pytorch-cpu
  - pytest
  - pytest-cov
  - pip:
      - ruamel.yaml
      - pymatgen
