name: xepy36
channels:
  - defaults
  - pytorch
  - rdkit
  - matsci
dependencies:
  - python=3.6
  - numpy
  - pandas
  - seaborn
  - requests
  - matplotlib
  - rdkit
  - plotly
  - scikit-learn
  - scipy
  - pytorch
  - pytest
  - pytest-cov
  - pymatgen
  - pip:
      - ruamel.yaml
