name: xepy37
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - pandas
  - seaborn
  - requests
  - matplotlib
  - rdkit
  - plotly
  - scikit-learn
  - scipy
  - pytorch
  - pytest
  - pytest-cov
  - pip:
      - ruamel.yaml
      - pymatgen
